### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by cherrytree456** [clarype/al_zonal_stats#2]
I tried running the zonal_stats_v2.py script the first time on a shapefile with about 1000 polyongs. it started by creating 120 empty shapefiles to hold the outputs, but then I received the error below.
![image](https://user-images.githubusercontent.com/36208703/206298484-1e2c7e9d-afaa-4bdc-a9ef-1f80677d5de2.png)

[zonal_stats_v2.txt](https://github.com/clarype/al_zonal_stats/files/10180095/zonal_stats_v2.txt)

**Comment by cherrytree456** [comment]
I tried running again this morning. I limited it to just one raster (d:\\recovery_testing\\fitted_index_out\\SACN_ftv_ENC.tif). This raster has 37 bands (1985-2021). The shapefile only has disturbances for three years 2010, 2011, 2012. This is the error I received this morning (which is same as yesterday). I've included the py script I'm running.
[zonal_stats_v3.txt](https://github.com/clarype/al_zonal_stats/files/10187596/zonal_stats_v3.txt)

![image](https://user-images.githubusercontent.com/36208703/206513088-587db10c-8114-49c9-a725-50124ec635ff.png)

**Comment by clarype** [comment]
Thanks for the error message I will take a look at it now!

**Comment by clarype** [comment]
Can I see what your CSV table looks like ?

**Comment by clarype** [comment]
I think I found the issue, and it is a logic error. The script make the assumption that delta images are always selected in the CSV file when that is not the case. So when it goes to merge the delta shape files there is nothing to merge. Thus, the code errors out.  I have made changes to the script, but this txt file (python) has your file paths. Give it a shot.

**Comment by cherrytree456** [comment]
Just tried the new script and it works fine. I'll keep testing to see if I can find anything else to break! Thanks!

**Comment by clarype** [comment]
Awesome, and thanks for breaking things! It is how code is made better!
